// SPDX-FileCopyrightText: 2025 Tillitis AB <tillitis.se>
// SPDX-License-Identifier: BSD-2-Clause

#ifndef TKEY_SYSCALL_NUM_H
#define TKEY_SYSCALL_NUM_H

enum syscall_num {
	TK1_SYSCALL_RESET = 1,
	TK1_SYSCALL_ALLOC_AREA = 2,
	TK1_SYSCALL_DEALLOC_AREA = 3,
	TK1_SYSCALL_WRITE_DATA = 4,
	TK1_SYSCALL_READ_DATA = 5,
	TK1_SYSCALL_ERASE_DATA = 6,
	TK1_SYSCALL_GET_VIDPID = 7,
	TK1_SYSCALL_PRELOAD_STORE = 8,
	TK1_SYSCALL_PRELOAD_STORE_FIN = 9,
	TK1_SYSCALL_PRELOAD_DELETE = 10,
	TK1_SYSCALL_PRELOAD_GET_METADATA = 11,
	TK1_SYSCALL_REG_MGMT = 12,
	TK1_SYSCALL_STATUS = 13,
	TK1_SYSCALL_GET_APP_DATA = 14,
	TK1_SYSCALL_PRELOAD_SET_PUBKEY = 15,
};

#endif
