M48
; DRILL file {KiCad (6.0.4)} date Mon Nov 14 14:09:30 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-14T14:09:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X5.436Y-2.1272
X5.627Y-2.1272
T2
X5.4242Y-2.0079
X5.6388Y-2.0079
T0
M30
