#!/bin/sh
set -eu

cd "${0%/*}"
cd ../../boards/mta1-usb-v1/test

if [ ! -e venv ]; then
  python3 -m venv venv
  . ./venv/bin/activate
  pip3 install -r requirements.txt
else
  . ./venv/bin/activate
fi

./reset.py
