
lint:
	autopep8 --in-place --max-line-length 70 --aggressive --aggressive usb_test.py icenvcm.py
	mypy --disallow-untyped-defs usb_test.py icenvcm.py
	pycodestyle --max-line-length 70 usb_test.py icenvcm.py
