#!/bin/sh
set -eu

if [ -e /etc/debian_version ]; then
  dpkg -s python3-venv || sudo apt install python3-venv
fi

# their current venv might have gone funky...
if [ -e venv ] && [ ! -e wipedonce ]; then
  rm -rf venv
  touch wipedonce
fi

if [ ! -e venv ]; then
  python3 -m venv venv
  . ./venv/bin/activate
  pip3 install -r requirements.txt
else
  . ./venv/bin/activate
fi

./production_test.py
